import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import Footer from "@/Component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "journey verse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div style={{minHeight:"100vh"}}>
          {children}
        </div>
      <Footer/>
      </body>
    </html>
  );
}
